### PR TITLE
Add softdtw loss and notebook

### PR DESCRIPTION
**Pull request by malfarhan7**
Add SoftDTW loss using the tslearn library in PyTorch. Also, include a notebook demonstrating FWI with SoftDTW.

### CODE REVIEW

**Comment by mrava87** [comment]
Great stuff @malfarhan7  :)

Will try to run the notebook to make sure everything works for another user and then approve. Just a question: is the last cell in the notebook meant to be there (it is not run and seems to be somehow a copy of previous ones?)

**Comment by malfarhan7** [comment]
Oh! Sorry, I forgot to delete the last cell.

**Comment by mrava87** [comment]
No worries, I'll do whilst finalizing the PR :)

**Comment by mrava87** [comment]
@malfarhan7 another question: why `wav=1e6*wav` is needed?

**Comment by malfarhan7** [comment]
The wavefield is in the order 1e-5 or 1e-6, and the loss becomes very small (zero). I think it is because of the log. The only way I could solve it was by scaling the data. In the older code version, the wavefield was in the order of 1e1, and I did not run into this issue. I also do 1e6*dobs_masked.

**Comment by mrava87** [comment]
Ok I see, then it makes completely sense. I missed this `1e6*dobs_masked`, which is why I was unsure how this would work. I'll lift this number up to avoid someone changing it in one place but not the other 😄

**Pull request merged**
